stages:
  - deploy

build:
  stage: deploy
  when: on_success
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/websciencecz/websciencecz .
    - docker push registry.gitlab.com/websciencecz/websciencecz
