version: '3'

services:
  web:
    image: httpd:2.4
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    environment:
      VIRTUAL_HOST: webscience.cz.test

networks:
  default:
    external:
      name: nginx-proxy
